# Generated by Django 5.2.1 on 2025-05-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_listing_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_for',
            field=models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], default='S', max_length=5, verbose_name='Listing for'),
        ),
    ]
