# Generated by Django 5.2.1 on 2025-05-11 17:06

import datetime
import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_listing_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ceiling_height',
        ),
        migrations.AddField(
            model_name='listing',
            name='facilities',
            field=models.TextField(blank=True, verbose_name='School Facilities (Library, Labs, Sports etc.)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_boarding',
            field=models.BooleanField(default=False, verbose_name='Boarding Available'),
        ),
        migrations.AddField(
            model_name='listing',
            name='languages_offered',
            field=models.CharField(blank=True, max_length=200, verbose_name='Languages Offered'),
        ),
        migrations.AddField(
            model_name='listing',
            name='religion',
            field=models.CharField(blank=True, choices=[('Catholic', 'Catholic'), ('Muslim', 'Muslim'), ('None', 'None')], max_length=50, verbose_name='Religious Affiliation'),
        ),
        migrations.AddField(
            model_name='listing',
            name='school_level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High', 'High School')], max_length=50, verbose_name='School Level'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Dorm Rooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='School Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='free_from',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Accepting Applications From'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(default=0, verbose_name='Parking Capacity'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to=listings.models.listing_dir_path, verbose_name='Main School Image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Show Online'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.FloatField(default=0, verbose_name='Lot size'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Tuition or Fee Estimate'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Heritage Site'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.FloatField(default=0, verbose_name='Campus Size (m²)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.listing', verbose_name='School'),
        ),
    ]
